### ISSUE TITLE
Why is Orcale cloud not listed and heliohost?

### ISSUE THREAD

**Issue by mendelsphotography** [cloudcommunity/Free-Hosting#12]
I see it says about free-for.dev website which has Oracle cloud free tier why is not listed here?
also heliohost they are a free hosting platform you can learn more on their website https://heliohost.org  They are currently moving still over from Cpanel to Plesk can learn more on their support page where they have a blog or their discord server. So free signups are not open right now but it's 100% legit and so far the only real free web hosting like that I came across they used to have Cpanel till they had an issue and now use Plesk.

**Comment by ubellavance** [comment]
This is a community effort. If you'd like to have something added, feel free to create a PR.

**Comment by mendelsphotography** [comment]
oh ofc. i just wanted to know before I did that if there was a reon.

**Comment by ubellavance** [comment]
Heliohost is part of the page linked in the php section.

**Comment by ubellavance** [comment]
For Oracle, it's in this repository: https://github.com/cloudcommunity/Cloud-Free-Tier-Comparison

**Comment by mendelsphotography** [comment]
ok thanks.
